#####################################
#                                   #
#  @author      : 00xWolf           #
#    GitHub    : @mmsaeed509       #
#    Developer : Mahmoud Mohamed   #
#  﫥  Copyright : Exodia OS        #
#                                   #
#####################################

# Themes Setting #
exodiaTheme = MSI Punk
background = /home/b4nd1t/Pictures/arch.jpg
color-scheme = MSI Punk
theme = Tokyonight-Dark-B
icons = candy-icons
cursor = Rage-Purple-Cursor
polybar = MSI Punk
change-betterlockscreen = true

# BSPWM Configurations, Appearance and Other Setting #
picom = default.conf
keybinding = sxhkdrc
multi-bar-monitors = false
keyboard-layouts = us
monitors-layouts = 

bsp-border-width = 2
bsp-window-gap = 10
bsp-split-ratio = 0.50
bsp-borderless-monocle = false
bsp-gapless-monocle = false
bsp-paddingless-monocle = false
bsp-single-monocle = false
bsp-focus-follows-pointer = true
bsp-presel-feedback = true
all-windows-float = false

# Predator Edition Setting #
RGB-keyboard = violet

# secret keys #
github-username = BTCxBANDITx
github-access-token =
weather-API = a473996e71819fc414e1aa41c3df6f74
weather-city-ID = 5807575

# Exodia OS Setting #
restore-user-config = false
exodia-assistant-auto-start = false
auto-update = true
