#####################################
#                                   #
#  @author      : 00xWolf           #
#    GitHub    : @mmsaeed509       #
#    Developer : Mahmoud Mohamed   #
#  﫥  Copyright : Exodia OS         #
#                                   #
#####################################

background = /home/b4nd1t/Pictures/arch.jpg
theme = Tokyonight-Dark-B
icons = candy-icons
cursor = Rage-Purple-Cursor
RGB-keyboard = violet
picom = default.conf
keybinding = sxhkdrc

bsp-border-width = 2
bsp-window-gap = 15
bsp-split-ratio = 0.50
bsp-borderless-monocle = true
bsp-gapless-monocle = false
bsp-paddingless-monocle = true
bsp-single-monocle = false
bsp-focus-follows-pointer = true
bsp-presel-feedback = true
